# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ad065a98e4274260d5c5968faf7cd9749d509fd527092156185095ca25880c9f0b21acd9ce0da04fcd3fbcc04d8837590334338ef173bc143f7f7f4774cf1c8

test:
  secret_key_base: 3c64f159d9d92821e286b5cab6938b67b060fd93cd16e6d3ce49e2a1e197ed8be75ce3f5d34819720dd6c82abfaf308e361adf51cbb85aec73c61823b458cc67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
